# conf/model/lightgbm.yaml
_target_: lightgbm.LGBMClassifier
n_estimators: 800
learning_rate: 0.05
num_leaves: 31
subsample: 0.8
colsample_bytree: 0.8
reg_lambda: 0.0
objective: binary
n_jobs: -1
random_state: ${seed}
