# conf/model/random_forest.yaml
_target_: sklearn.ensemble.RandomForestClassifier
n_estimators: 600
random_state: ${seed}
n_jobs: -1
class_weight: balanced
max_depth: null
min_samples_split: 2
min_samples_leaf: 1
