# conf/model/xgboost.yaml
_target_: xgboost.XGBClassifier
n_estimators: 800
learning_rate: 0.05
max_depth: 6
subsample: 0.8
colsample_bytree: 0.8
min_child_weight: 1
gamma: 0
reg_lambda: 1.0
objective: "binary:logistic"
eval_metric: "logloss"
tree_method: "hist"
n_jobs: -1
random_state: ${seed}
