# conf/preprocess/onehot_dense.yaml
# 트리 계열(특히 RandomForest)이 sparse 입력을 못 받는 경우가 많아서 "dense 원핫" 기본값
remainder: drop
sparse_threshold: 0.0  # 0이면 사실상 dense로 만드는 효과(전체 결합 결과가 sparse로 떨어지는 걸 방지)

numeric:
  steps:
    - name: imputer
      transformer:
        _target_: sklearn.impute.SimpleImputer
        strategy: median

categorical:
  steps:
    - name: imputer
      transformer:
        _target_: sklearn.impute.SimpleImputer
        strategy: most_frequent
    - name: onehot
      transformer:
        _target_: ${project.module}.make_onehot
        handle_unknown: ignore
        sparse_output: false
