# conf/preprocess/standardize_onehot_sparse.yaml
# 수치형 표준화 + 희소 원핫 (선형모델에 흔한 조합)
remainder: drop
sparse_threshold: 1.0

numeric:
  steps:
    - name: imputer
      transformer:
        _target_: sklearn.impute.SimpleImputer
        strategy: median
    - name: scaler
      transformer:
        _target_: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true

categorical:
  steps:
    - name: imputer
      transformer:
        _target_: sklearn.impute.SimpleImputer
        strategy: most_frequent
    - name: onehot
      transformer:
        _target_: ${project.module}.make_onehot
        handle_unknown: ignore
        sparse_output: true
