# conf/preprocess/target_encoder.yaml
# TargetEncoder: 범주형을 타깃 평균 기반으로 수치화 (dense 출력)
# 필요: pip install category_encoders
remainder: drop
sparse_threshold: 0.0

numeric:
  steps:
    - name: imputer
      transformer:
        _target_: sklearn.impute.SimpleImputer
        strategy: median
    - name: scaler
      transformer:
        _target_: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true

categorical:
  steps:
    - name: imputer
      transformer:
        _target_: sklearn.impute.SimpleImputer
        strategy: most_frequent
    - name: target_encoder
      transformer:
        _target_: category_encoders.target_encoder.TargetEncoder
        smoothing: 10.0
        min_samples_leaf: 20
        handle_unknown: value
        handle_missing: value
