# conf/sampler/borderline_smote.yaml
# 필요: pip install imbalanced-learn
# BorderlineSMOTE: 경계 샘플에 집중 (m_neighbors 포함)
enable: true
sampler:
  _target_: imblearn.over_sampling.BorderlineSMOTE
  random_state: ${seed}

  sampling_strategy: auto
  k_neighbors: 5
  m_neighbors: 10            # int (majority NN)
  kind: borderline-1         # borderline-1 | borderline-2
