# conf/sampler/random_under.yaml
# 필요: pip install imbalanced-learn
# RandomUnderSampler: 다수 클래스 언더샘플링
enable: true
sampler:
  _target_: imblearn.under_sampling.RandomUnderSampler
  random_state: ${seed}

  # --- 핵심 sweep 축 ---
  sampling_strategy: auto     # auto | majority | not minority | float | dict
  replacement: false          # true면 복원추출
