# conf/sampler/smotetomek.yaml
# 필요: pip install imbalanced-learn
# SMOTE + TomekLinks 결합 (경계 정리)
enable: true
sampler:
  _target_: imblearn.combine.SMOTETomek
  random_state: ${seed}

  sampling_strategy: auto

  smote:
    _target_: imblearn.over_sampling.SMOTE
    random_state: ${seed}
    sampling_strategy: auto
    k_neighbors: 5

  tomek:
    _target_: imblearn.under_sampling.TomekLinks
    sampling_strategy: auto
