# conf/sampler/smote.yaml
# 필요: pip install imbalanced-learn
# 가장 기본적인 SMOTE (dense 입력 권장)
enable: true
sampler:
  _target_: imblearn.over_sampling.SMOTE
  random_state: ${seed}

  # --- 핵심 sweep 축 ---
  sampling_strategy: auto     # auto | minority | not majority | float(0~1) | dict
  k_neighbors: 5              # int (minority NN)
